export const GET_WEATHER_INITIAL = 'GET_WEATHER_INITIAL';
export const GET_WEATHER_START = 'GET_WEATHER_START';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAILED = 'GET_WEATHER_FAILED';
